const RESULTADOS_MININTERIOR_GOB_AR_API_BASE_URL: string = 'https://resultados.mininterior.gob.ar/api';
const RESULTADOS_MININTERIOR_GOB_AR_API_RESULTADOS_URL: string = `${RESULTADOS_MININTERIOR_GOB_AR_API_BASE_URL}/resultados`;

export {
    RESULTADOS_MININTERIOR_GOB_AR_API_RESULTADOS_URL,
}