const DEFAULT_PORT: number = 3000;

const RESULTADOS_MININTERIOR_GOB_AR_API_BASE_URL: string = 'https://resultados.mininterior.gob.ar/api';
const RESULTADOS_MININTERIOR_GOB_AR_API_RESULTADOS_URL: string = `${RESULTADOS_MININTERIOR_GOB_AR_API_BASE_URL}/resultados`;

const RATE_LIMITER_WINDOW_MINUTES: number = 1;
const RATE_LIMITER_REQUEST_PER_WINDOW: number = 100;

export {
    DEFAULT_PORT,
    RESULTADOS_MININTERIOR_GOB_AR_API_RESULTADOS_URL,
    RATE_LIMITER_WINDOW_MINUTES,
    RATE_LIMITER_REQUEST_PER_WINDOW,
}